#!/bin/sh

src=originals
dest=term

# These don't convert (no lines match highlight commands)
# astronaut.vim
# calmar256-dark.vim
# calmar256-light.vim
# desert256.vim
# impact.vim
# jellybeans.vim
# summerfruit256.vim
# wombat256.vim
#
# This doesn't convert due to weird color names:
# nightshimmer.vim

convertable='
    adaryn.vim
    adrian.vim
    aiseered.vim
    anotherdark.vim
    aqua.vim
    asu1dark.vim
    autumn2.vim
    autumnleaf.vim
    autumn.vim
    baycomb.vim
    bclear.vim
    biogoo.vim
    blacksea.vim
    bluegreen.vim
    borland.vim
    breeze.vim
    brookstream.vim
    buttercream.vim
    camo.vim
    candycode.vim
    candy.vim
    chela_light.vim
    chocolateliquor.vim
    clarity.vim
    cleanphp.vim
    colorer.vim
    dante.vim
    darkblue2.vim
    darkbone.vim
    darkslategray.vim
    darkspectrum.vim
    darkZ.vim
    dawn.vim
    denim.vim
    desertEx.vim
    dusk.vim
    dw_blue.vim
    dw_cyan.vim
    dw_green.vim
    dw_orange.vim
    dw_purple.vim
    dw_red.vim
    dw_yellow.vim
    earendel.vim
    eclipse.vim
    ekvoli.vim
    fine_blue2.vim
    fine_blue.vim
    fnaqevan.vim
    fog.vim
    freya.vim
    fruit.vim
    fruity.vim
    golden.vim
    guardian.vim
    habilight.vim
    herald.vim
    inkpot.vim
    ir_black.vim
    ironman.vim
    jammy.vim
    kellys.vim
    leo.vim
    lettuce.vim
    lucius.vim
    manxome.vim
    marklar.vim
    maroloccio.vim
    martin_krischik.vim
    matrix.vim
    molokai.vim
    moria.vim
    moss.vim
    motus.vim
    mustang.vim
    navajo-night.vim
    navajo.vim
    neon.vim
    neverness.vim
    night.vim
    no_quarter.vim
    northland.vim
    nuvola.vim
    oceanblack.vim
    oceandeep.vim
    oceanlight.vim
    olive.vim
    papayawhip.vim
    peaksea.vim
    print_bw.vim
    pyte.vim
    railscasts2.vim
    railscasts.vim
    rdark.vim
    relaxedgreen.vim
    robinhood.vim
    rootwater.vim
    satori.vim
    sea.vim
    settlemyer.vim
    sienna.vim
    silent.vim
    simpleandfriendly.vim
    softblue.vim
    soso.vim
    spring.vim
    synic.vim
    tabula.vim
    tango2.vim
    tango.vim
    taqua.vim
    tcsoft.vim
    tir_black.vim
    tolerable.vim
    torte.vim
    twilight.vim
    two2tango.vim
    vc.vim
    vibrantink.vim
    vividchalk.vim
    vylight.vim
    winter.vim
    wombat.vim
    wood.vim
    wuye.vim
    xemacs.vim
    xoria256.vim
    zenburn.vim
    zmrok.vim
'

for f in $convertable ; do
    ./scripts/convert $src/$f > $dest/$f
done
