#!/usr/bin/env python

import sys
import os

import fabricate

# These are weird about the background option:
# satori.vim (never sets background or any group background)
#
# These observe background:
# baycomb.vim
# earendel.vim
# moria.vim
# peaksea.vim
# sienna.vim (actually uses its own variable, but same principle)
#
# These use exec:
# astronaut.vim (variable expansion)
# calmar256-dark.vim (crazy table stuff)
# calmar256-light.vim (crazy table stuff)
# marklar.vim (variable expansion)
# twilight.vim (variable expansion)
# two2tango.vim (variable expansion)
#

dark_schemes = [
    'adaryn.vim',
    'adrian.vim',
    'aiseered.vim',
    'anotherdark.vim',
    'aqua.vim',
    'asu1dark.vim',
    'BlackSea.vim',
    'bluegreen.vim',
    'borland.vim',
    'breeze.vim',
    'brookstream.vim',
    'camo.vim',
    'candycode.vim',
    'candy.vim',
    'ChocolateLiquor.vim',
    'clarity.vim',
    'cleanphp.vim',
    'colorer.vim',
    #'dante.vim',
    'darkblue2.vim',
    'darkbone.vim',
    'darkslategray.vim',
    'darkspectrum.vim',
    'darkZ.vim',
    'denim.vim',
    'desertEx.vim',
    'dusk.vim',
    'dw_blue.vim',
    'dw_cyan.vim',
    'dw_green.vim',
    'dw_orange.vim',
    'dw_purple.vim',
    'dw_red.vim',
    'dw_yellow.vim',
    #'ekvoli.vim',
    'fnaqevan.vim',
    'freya.vim',
    'fruity.vim',
    'golden.vim',
    'guardian.vim',
    'herald.vim',
    'inkpot.vim',
    'ir_black.vim',
    'jammy.vim',
    'kellys.vim',
    'leo.vim',
    'lucius.vim',
    'manxome.vim',
    #'maroloccio.vim',
    'matrix.vim',
    'molokai.vim',
    'moss.vim',
    'motus.vim',
    'mustang.vim',
    'navajo-night.vim',
    'neon.vim',
    'neverness.vim',
    'nightshimmer.vim',
    'night.vim',
    'no_quarter.vim',
    'northland.vim',
    'oceanblack.vim',
    'oceandeep.vim',
    'olive.vim',
    'railscasts.vim',
    'rdark.vim',
    'relaxedgreen.vim',
    'robinhood.vim',
    'rootwater.vim',
    'sea.vim',
    'settlemyer.vim',
    'softblue.vim',
    'synic.vim',
    'tabula.vim',
    'tango2.vim',
    'tango.vim',
    'tir_black.vim',
    'torte.vim',
    'vibrantink.vim',
    #'vividchalk.vim',
    'wombat.vim',
    'wood.vim',
    'wuye.vim',
    'xemacs.vim',
    'xoria256.vim',
    'zenburn.vim',
    'zmrok.vim',
]

light_schemes = [
    'autumn2.vim',
    'autumnleaf.vim',
    'autumn.vim',
    'bclear.vim',
    'biogoo.vim',
    'buttercream.vim',
    'chela_light.vim',
    'dawn.vim',
    'eclipse.vim',
    'fine_blue.vim',
    'fog.vim',
    'fruit.vim',
    'habiLight.vim',
    'ironman.vim',
    'martin_krischik.vim',
    'navajo.vim',
    'nuvola.vim',
    'oceanlight.vim',
    'PapayaWhip.vim',
    'print_bw.vim',
    'pyte.vim',
    'silent.vim',
    'simpleandfriendly.vim',
    'soso.vim',
    'spring.vim',
    'taqua.vim',
    'tcsoft.vim',
    'tolerable.vim',
    'vc.vim',
    'vylight.vim',
    'winter.vim',
]

patch_only = [
    'desert256.vim',
    'jellybeans.vim',
    'lettuce.vim',
    'summerfruit256.vim',
    'wombat256.vim',
    #'impact.vim', # Terminal only
]

def mkdir(path):
    try:
        os.makedirs(path)
    except OSError:
        pass

def patch(scheme):
    patch_file = os.path.join('patches', scheme + '.diff')
    if os.path.exists(patch_file):
        fabricate.run('sh', '-c',
                      'patch -p0 -o patched/%s originals/%s < %s' %
                      (scheme, scheme, patch_file))
    else:
        fabricate.run('cp', os.path.join('originals', scheme), 'patched/')

def build():
    mkdir('patched')
    for scheme in dark_schemes + light_schemes + patch_only:
        patch(scheme)

    mkdir('term')
    for scheme in dark_schemes:
        fabricate.run('sh', '-c', './scripts/gui2xterm patched/' +
                                  scheme + ' > term/' + scheme)

    for scheme in light_schemes:
        fabricate.run('sh', '-c', './scripts/gui2xterm --light patched/' +
                                  scheme + ' > term/' + scheme)

    for scheme in patch_only:
        fabricate.run('cp', 'patched/' + scheme, 'term/')

if __name__ == '__main__':
    fabricate.main()
