#!/usr/bin/env python

import sys
import optparse
import re

import color

class HighlightLine(object):
    _hi_matcher = re.compile(r'''
        (?P<head>\s*"?\s*)     # catches commented-out lines also
        (?P<command>
            hi(g(h(l(i(g(ht?)?)?)?)?)?)?
            \s+
        )
        (?P<groupname>[A-Za-z0-9]+)
        (?P<params>(
            \s+
            (cterm[fb]g|c?term|start|stop|gui(fg|bg|sp)?|font)
            =
            [^ \t\n]+          # NOTE: doesn't match quoted values
        )+)
        (?P<tail>
            [ \t]*             # optional whitespace
            ("[^\n]*)?         # optional comment
            \n?                # optional newline
        )
    ''', re.VERBOSE)

    def __init__(self, line):
        m = self._hi_matcher.match(line)
        if m is None:
            raise NoHighlightMatch()

        self._head = '%s%s%s' % (m.group('head'), m.group('command'),
                                 m.group('groupname'))
        self._params = m.group('params')
        self._tail = m.group('tail')

    _param_matcher = re.compile(r'''
        (?P<param>(cterm[fb]g|c?term|start|stop|gui(fg|bg|sp)?|font))
        =
        (?P<value>[^ \t]+)
    ''', re.VERBOSE)

    def get_param(self, param):
        '''
        Return the value for the given param, or None if the param doesn't
        exist in the line.
        '''
        for m in self._param_matcher.finditer(self._params):
            if m.group('param') == param:
                return m.group('value')

        return None

    def _replace(self, new_params, match):
        '''
        Helper for updated().
        '''
        param = match.group('param')
        if param in new_params:
            value = new_params[param]
            new_params.pop(param)
            return '%s=%s' % (param, value)
        else:
            return match.group()

    def updated(self, new_params):
        '''
        Return a new line using new_params. The new parameters replace
        existing parameters when possible, or they get appended to the line.
        '''
        unused_params = dict(new_params)
        repl = lambda m: self._replace(unused_params, m)
        param_str = self._param_matcher.sub(repl, self._params)

        append_params = ' '.join('%s=%s' % (param, value)
                                 for (param, value) in unused_params.items())
        if append_params:
            append_params = ' ' + append_params

        return '%s%s%s%s' % (self._head, param_str, append_params, self._tail)

class NoHighlightMatch(ValueError):
    pass

def cterm_color(gui_color):
    '''
    Return the cterm color corresponding to gui_color. This might not be a
    color at all if gui_color is none, fg, or bg.
    '''
    if gui_color.lower() in ('none', 'fg', 'bg'):
        return gui_color

    c = color.Color.from_string(gui_color)
    return c.nearest_xterm()

def cterm_attrs(gui_attrs):
    '''
    Return the cterm attributes based on gui_attrs. This means dropping
    attributes that don't work on the terminal.
    '''
    if gui_attrs.lower() == 'none':
        return gui_attrs

    attrs = [attr.strip() for attr in gui_attrs.split(',')]
    new_attrs = []
    for attr in attrs:
        if attr.lower() in ('bold', 'underline', 'reverse', 'inverse'):
            new_attrs.append(attr)

    if new_attrs:
        return ','.join(new_attrs)
    else:
        return 'NONE'

def find_params(hl):
    '''
    Find cterm parameters based on existing gui parameters.
    '''
    result = {}

    gui = hl.get_param('gui')
    if gui:
        result['cterm'] = cterm_attrs(gui)

    guifg = hl.get_param('guifg')
    if guifg:
        result['ctermfg'] = cterm_color(guifg)

    guibg = hl.get_param('guibg')
    if guibg:
        result['ctermbg'] = cterm_color(guibg)

    return result

def parse_args(args):
    # There are no actual options at the moment.
    parser = optparse.OptionParser()

    (opts, arguments) = parser.parse_args(args)
    return (opts, arguments)

def main(args=None):
    if args is None:
        args = sys.argv[1:]

    global opts
    (opts, arguments) = parse_args(args)

    assert len(arguments) == 1
    filename = arguments[0]

    for line in open(filename):
        try:
            hl = HighlightLine(line)
            params = find_params(hl)
            sys.stdout.write(hl.updated(params))
        except NoHighlightMatch:
            sys.stdout.write(line)

    return 0

if __name__ == '__main__':
    sys.exit(main())
