#!/usr/bin/env python

import sys

tag = '''\
" NOTE: This colorscheme has been modified from the original. The changes are
" primarily to add (or modify) 256-color xterm support, but may include other
" changes also (e.g., bug fixes). Details can be found at:
" http://github.com/KevinGoodsell/vim-xterm-colors
'''

def main(args=None):
    if args is None:
        args = sys.argv[1:]

    assert len(args) == 2

    (infile, outfile) = args

    data = open(infile).read()
    out = open(outfile, 'w')
    out.write(data.replace('" VIM-XTERM-TAG\n', tag))

if __name__ == '__main__':
    sys.exit(main())
